name: test and publish
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gradle tests
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .gradle
            build
  publish:
    # TODO: uncomment this when im done testing
    # if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
      - name: gradle publish
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
        with:
          args: publishToMavenLocal
      - name: checkout repo
        run: cd ~/ && git clone https://github.com/DetachHead/maven.git
      - name: commit and push published package
        run: mv ~/m2/repository ./maven && git commit -am "publish $GITHUB_SHA" && git push
