name: test and publish
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: ./gradlew check
  publish:
    # TODO: uncomment this when im done testing
    # if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    env:
      MAVEN_REPO: github.com/DetachHead/maven.git
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: ./gradlew publishToMavenLocal
      - name: checkout repo
        run: cd ~/ && git clone https://$MAVEN_REPO
      - name: commit and push published package
        run: |
          yes | cp -rf ~/.m2/repository ./maven
          cd maven
          git config --global user.name 'github actions'
          git config --global user.email 'your-username@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@$MAVEN_REPO
          git add -A
          git commit -m "publish $GITHUB_SHA" && git push
